apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
    app: {{ template "rancher.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  secretName: tls-rancher
  dnsNames:
  - {{ .Values.hostname }}
  - www.{{ .Values.hostname }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.hostname }}
      - www.{{ .Values.hostname }}
  issuerRef:
    name: {{ template "rancher.fullname" . }}
    kind: Issuer
