apiVersion: v1
name: rancher
version: 2.0.6
description: Install Rancher Server to manage Kubernetes clusters across providers.
keywords:
  - rancher
home: https://www.design4.pro
sources:
  - https://github.com/design4pro/charts
maintainers:
  - name: DESIGN4PRO
    email: dev@design4.pro
    url: https://www.design4.pro
icon: https://github.com/rancher/ui/blob/master/public/assets/images/logos/welcome-cow.svg
appVersion: v2.0.6
